name: fix-code-style

on:
  push:

jobs:
  fix-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Set up Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          composer install --no-interaction
      - name: Run Pint
        run: composer pint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: fix code style"
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
